### ISSUE TITLE
[Feature Request] Share Intent URL (or just a query param?)

### ISSUE THREAD

**Issue by viscountexx** [ptero-app/ptero#1]
This may be a little bit silly, and it's of no high priority, but:

In Mastodon, you can use a Share intent URL, available at: https://example.instance/share?text=

The "text" query parameter will then be, after URL decoding of course, pre-filled into the textbox of a mastodon post page. I use this with Retrospring (an anonymous Q&A service), as it can automatically put a partial answer & question + link to the full post, into the share text query parameter of any URL you give it.

Given Ptero is already just a post box in its webpage, you could honestly just add an autofilling query parameter to the page without even needing a separate URL.

Feel free to decline this if it's out of scope or anything!

**Comment by sleepdeprecation** [comment]
I just want to make sure I'm parsing this request properly, you're asking for the ability to click a link like `https://ptero.app/share?text=<blah>`?

Honestly that should be pretty easy, I want to add real support for opening to a specific tab, so this should be doable with that!

**Comment by viscountexx** [comment]
Yup!!

**Comment by sleepdeprecation** [comment]
This is working on going live right now, it's just `?text=<whatever>`, so `https://ptero.app?text=some%20fun%20text` should automatically put `some fun text` in the text area

**Comment by viscountexx** [comment]
Thank you so much!

**Comment by sleepdeprecation** [comment]
oops! not ready yet, I didn't type-check before pushing so the build failed, one sec.

**Comment by viscountexx** [comment]
testing and checking things before pushing to prod is for cowards, i respect you more now (lol)

**Comment by sleepdeprecation** [comment]
okay, now it should be working

**Comment by viscountexx** [comment]
Works! And the UI looks snazzier than last time I refreshed it, nice!

**Comment by sleepdeprecation** [comment]
oh yeah! i did a little work this afternoon after debugging an issue with someone, updated the ui to be more than the vanilla html elements, and added the ability to modify logins in case you added one but mistyped the server or password or something
